[package]
name = "sync-service"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "ssh-sync-service"
path = "src/main.rs"

[dependencies]
policy-engine = { path = "../../crates/policy-engine" }
storage-sqlite = { path = "../../crates/storage-sqlite" }
sync-core = { path = "../../crates/sync-core" }

