/* Generated by scripts/generate-abi.mjs - do not edit by hand. */
/* ABI codegen version: 1.0.0 */
#ifndef SSH_ABI_H
#define SSH_ABI_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define SSH_ABI_SCHEMA_VERSION 1u
#define SSH_ABI_CODEGEN_VERSION "1.0.0"
#define SSH_ABI_HEADER_SIZE 32u
#define SSH_ABI_FIELD_COUNT 7u
#define SSH_ABI_FIELD_SCHEMA_VERSION 0u
#define SSH_ABI_FIELD_MESSAGE_TYPE 1u
#define SSH_ABI_FIELD_BYTE_LEN 2u
#define SSH_ABI_FIELD_REQUEST_ID 3u
#define SSH_ABI_FIELD_CANCEL 4u
#define SSH_ABI_FIELD_BACKPRESSURE 5u
#define SSH_ABI_FIELD_ERROR_CODE 6u

#define SSH_ABI_OFFSET_SCHEMA_VERSION 0u
#define SSH_ABI_OFFSET_MESSAGE_TYPE 4u
#define SSH_ABI_OFFSET_BYTE_LEN 8u
#define SSH_ABI_OFFSET_REQUEST_ID 16u
#define SSH_ABI_OFFSET_CANCEL 24u
#define SSH_ABI_OFFSET_BACKPRESSURE 25u
#define SSH_ABI_OFFSET_ERROR_CODE 28u

typedef struct ssh_abi_message_header {
    uint32_t schema_version;   /* offset 0 */
    uint32_t message_type;   /* offset 4 */
    uint64_t byte_len;   /* offset 8 */
    uint64_t request_id;   /* offset 16 */
    uint8_t cancel;   /* offset 24 */
    uint8_t backpressure;   /* offset 25 */
    uint32_t error_code;   /* offset 28 */
} ssh_abi_message_header;

uint32_t ssh_abi_version(void);
const char *ssh_abi_codegen_version(void);
uint64_t ssh_abi_header_size(void);
uint64_t ssh_abi_field_offset(uint32_t field);
int32_t ssh_abi_header_is_valid(uint32_t schema_version);
int32_t ssh_abi_validate_field_offsets(void);

#ifdef __cplusplus
}
#endif

#endif /* SSH_ABI_H */
