[package]
name = "abi-c"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]

[dependencies]
core-domain = { path = "../core-domain" }
core-errors = { path = "../core-errors" }
core-protocol = { path = "../core-protocol" }
session-orchestrator = { path = "../session-orchestrator" }

