#!/usr/bin/env node

// Deterministic generator for crates/abi-c/include/ssh_abi.h (T097).
// Regenerating must produce a byte-identical file; CI detects drift by
// regenerating and diffing against the checked-in header.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

const CODEGEN_VERSION = '1.0.0';
const SCHEMA_VERSION = 1;
const HEADER_SIZE = 32;
const FIELD_COUNT = 7;

// field id -> (macro suffix, byte offset)
const FIELDS = [
  ['SCHEMA_VERSION', 0],
  ['MESSAGE_TYPE', 4],
  ['BYTE_LEN', 8],
  ['REQUEST_ID', 16],
  ['CANCEL', 24],
  ['BACKPRESSURE', 25],
  ['ERROR_CODE', 28],
];

function renderHeader() {
  const lines = [];
  lines.push('/* Generated by scripts/generate-abi.mjs - do not edit by hand. */');
  lines.push(`/* ABI codegen version: ${CODEGEN_VERSION} */`);
  lines.push('#ifndef SSH_ABI_H');
  lines.push('#define SSH_ABI_H');
  lines.push('');
  lines.push('#include <stdint.h>');
  lines.push('');
  lines.push('#ifdef __cplusplus');
  lines.push('extern "C" {');
  lines.push('#endif');
  lines.push('');
  lines.push(`#define SSH_ABI_SCHEMA_VERSION ${SCHEMA_VERSION}u`);
  lines.push(`#define SSH_ABI_CODEGEN_VERSION "${CODEGEN_VERSION}"`);
  lines.push(`#define SSH_ABI_HEADER_SIZE ${HEADER_SIZE}u`);
  lines.push(`#define SSH_ABI_FIELD_COUNT ${FIELD_COUNT}u`);
  FIELDS.forEach(([suffix, offset], index) => {
    lines.push(`#define SSH_ABI_FIELD_${suffix} ${index}u`);
  });
  lines.push('');
  FIELDS.forEach(([suffix, offset]) => {
    lines.push(`#define SSH_ABI_OFFSET_${suffix} ${offset}u`);
  });
  lines.push('');
  lines.push('typedef struct ssh_abi_message_header {');
  const types = {
    SCHEMA_VERSION: 'uint32_t',
    MESSAGE_TYPE: 'uint32_t',
    BYTE_LEN: 'uint64_t',
    REQUEST_ID: 'uint64_t',
    CANCEL: 'uint8_t',
    BACKPRESSURE: 'uint8_t',
    ERROR_CODE: 'uint32_t',
  };
  FIELDS.forEach(([suffix, offset]) => {
    const fieldName = suffix.toLowerCase();
    const type = types[suffix];
    lines.push(`    ${type} ${fieldName};   /* offset ${offset} */`);
  });
  lines.push('} ssh_abi_message_header;');
  lines.push('');
  lines.push('uint32_t ssh_abi_version(void);');
  lines.push('const char *ssh_abi_codegen_version(void);');
  lines.push('uint64_t ssh_abi_header_size(void);');
  lines.push('uint64_t ssh_abi_field_offset(uint32_t field);');
  lines.push('int32_t ssh_abi_header_is_valid(uint32_t schema_version);');
  lines.push('int32_t ssh_abi_validate_field_offsets(void);');
  lines.push('');
  lines.push('#ifdef __cplusplus');
  lines.push('}');
  lines.push('#endif');
  lines.push('');
  lines.push('#endif /* SSH_ABI_H */');
  lines.push('');
  return lines.join('\n');
}

const outDir = resolve(process.argv[2] ?? join(import.meta.dirname, '..', 'crates', 'abi-c', 'include'));
const outFile = join(outDir, 'ssh_abi.h');
mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, renderHeader(), 'utf8');
console.log(`generated ${outFile} (codegen ${CODEGEN_VERSION})`);